/**
 * DVSViewer — Concept Diagram Renderer
 * Renders inline SVG visual scaffolds generated by the DVS subsystem.
 */
import { useState } from 'react';
import { BarChart2, ChevronDown, ChevronUp } from 'lucide-react';

interface DVSViewerProps {
  svgPayload: string;
}

export default function DVSViewer({ svgPayload }: DVSViewerProps) {
  const [hidden, setHidden] = useState(false);

  return (
    <div className="dvs-container">
      <div className="dvs-header">
        <div className="dvs-label">
          <BarChart2 size={15} style={{ color: 'var(--green-600)' }} />
          <span className="dvs-title">Concept Diagram</span>
          <span className="dvs-subtitle">Auto-generated to clarify this concept</span>
        </div>
        <button
          className="dvs-toggle"
          onClick={() => setHidden(h => !h)}
          aria-label={hidden ? 'Show diagram' : 'Collapse diagram'}
        >
          {hidden ? <><ChevronDown size={13} /> Show</> : <><ChevronUp size={13} /> Hide</>}
        </button>
      </div>

      {!hidden && (
        <div
          className="dvs-svg-wrapper"
          dangerouslySetInnerHTML={{ __html: svgPayload }}
          aria-label="Educational concept diagram"
        />
      )}
    </div>
  );
}
